# Generated by Django 3.2.4 on 2021-06-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('investment_returns', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
