# Generated by Django 3.2.4 on 2021-06-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_api', '0002_rename_investmentmodel_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_returns',
            new_name='investmentreturns',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='user_name',
            new_name='username',
        ),
    ]
