# Generated by Django 3.2.4 on 2021-06-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_api', '0004_rename_username_investment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='name',
            new_name='username',
        ),
    ]
