# Generated by Django 3.2.4 on 2021-06-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_api', '0006_rename_investmentreturns_investment_investmentreturns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investmentReturns',
            field=models.IntegerField(blank=True),
        ),
    ]
