# Generated by Django 3.2.4 on 2021-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_api', '0009_alter_investment_investmentreturns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investmentReturns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
