# Generated by Django 3.2.4 on 2021-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_api', '0010_alter_investment_investmentreturns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investmentReturns',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
